version: '3.8'
services:
  web:
    build:
      context: ./packages/probot
      target: dev
    volumes:
      - .:/src
      - ./pk.pem:/app/pk.pem:ro
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

