name: Prettier
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  prettier:
    name: Do the files need to be linted?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npx yarn install --frozen-lockfile
      - run: yarn lint
